import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youtube",
  description: "Generated by create next app",
};

export default function YoutubeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-5">
        <span>Header youtube</span>
        <div>{children}</div>
    </div>
  );
}
